### ISSUE TITLE
SYSTEM locks in, cannot use option to logout (BatOS 11.1)

### ISSUE THREAD

**Issue by XDuskAshes** [cool-strawberry/BatOS#1]
![image](https://github.com/cool-strawberry/BatOS/assets/101196233/165e5e36-aaf6-47bf-b48b-ed1a2add21c9)

Whenever I use the SYSTEM user in BatOS 11.1, I can't logout. This happens with no other account.

**Comment by cool-strawberry** [comment]
Does it crash when you try to log out?

**Comment by astric32dll** [comment]
Fixed in BatOS 11.5.

**Comment by astric32dll** [comment]
Fixed!

pon., 10 lip 2023 o 08:56 XDuskAshesReal ***@***.***>
napisał(a):
