### ISSUE TITLE
BatOS 14.0, minor issue that can be annoying to the user experience

### ISSUE THREAD

**Issue by XDuskAshes** [cool-strawberry/BatOS#2]
The title of the window is still "BatOS 13.5". Having the title match the version improves user experience and engagement. This has happened with previous versions, however it was fixed relatively fast (notably BatOS 11.5, to memory)

**Comment by astric32dll** [comment]
Sorry for the very late reply, but this has already been fixed in BatOS 14.5

Thanks,
cool strawberry

śr., 9 sie 2023 o 12:01 XDuskAshesReal ***@***.***>
napisał(a):
